- name: playbook using variables
  hosts: localhost
  vars: 
    Course: "Devops"
    Trainer: "Sivakumar"
  tasks:
  - name: variables in playbook
    ansible.builtin.debug:
      msg: "Hi, I am Learning {{Course}}, Trainer is {{Trainer}}"

