- name: playbook using variables
  hosts: localhost
  vars_files: 
  - variables.yaml    
  tasks:
  - name: variables in playbook
    ansible.builtin.debug:
      msg: "Hi, I am Learning {{Course}}, Trainer is {{Trainer}}"

